//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWeatherInfo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherTable
    {
        public long Id { get; set; }
        public string InsertDate { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string CodeImage { get; set; }
        public string DateTime { get; set; }
        public string Temperature_1 { get; set; }
        public string WeatherInfo_1 { get; set; }
        public string WindInfo_1 { get; set; }
        public string Image_1_1 { get; set; }
        public string Image_1_2 { get; set; }
        public string WeatherDetail_1_1 { get; set; }
        public string WeatherDetail_1_2 { get; set; }
        public string Temperature_2 { get; set; }
        public string WeatherInfo_2 { get; set; }
        public string WindInfo_2 { get; set; }
        public string Image_2_1 { get; set; }
        public string Image_2_2 { get; set; }
        public string Temperature_3 { get; set; }
        public string WeatherInfo_3 { get; set; }
        public string WindInfo_3 { get; set; }
        public string Image_3_1 { get; set; }
        public string Image_3_2 { get; set; }
        public string CityNotes { get; set; }
    }
}
